### ISSUE TITLE
question about prcurve matlab

### ISSUE THREAD

**Issue by Miraclelzk** [irapkaist/scancontext#10]
I looked at the prcurve generated in the fast evaluator. I can't understand the role of **num_top_n** in main.m. Only the first line is taken in prcurve_drawer.m, I can’t understand why and how to do it.

In this position
```
%% Params 
FigIdx = 2;
figure(FigIdx); clf;

TopNindexes = [1];
name = 'top1';

nTopNindexes = length(TopNindexes);
```

**Comment by kissb2** [comment]
you can ignore that :)

That part is just a legacy of my past research 
when I tested my RAL paper's algorithm 
I had evaluated the performance of the top N estimates 
 (i.e., if you retrieved 50 nearest ones from the database, and if the true answer is in those 50, then you consider your answer is correct)

truly the top 1 performance is actually helpful for the practical SLAM in the real world
so I omitted that part (consider answer or not up to top N) because this repository aims place recognition for SLAM
but the code's structure legacy has remained. 

Sorry for the confusing, I note again you can ignore that part (i.e., you can just use [1] as it is), and please enjoy the evaluator. 

Thank you.

**Comment by Miraclelzk** [comment]
Thank you, sacancontext is a simple and effective method, I have benefited a lot from it.
