### ISSUE TITLE
how to run matlab samples

### ISSUE THREAD

**Issue by monage2018** [irapkaist/scancontext#5]
Hi,
   I  modify the vel_dir = '/home/gaolixu/scancontext/sample_data/KITTI/00/velodyne',  and i run run "PlaceRecognizer" directly.
  there is no file from "000001.bin" to "000450.bin" in your sample_data file.
  so can you give me the url, then i can download the full raw velodyne data.
Thank you

**Comment by kissb2** [comment]
Thank you for your interest. 

You should download KITTI velodyne files and unzip it 
(That is, "Download odometry data set (velodyne laser data, 80 GB)" from http://www.cvlibs.net/datasets/kitti/eval_odometry.php)

Then the directory name would be like ".... your path ... /00/velodyne/"

**Comment by monage2018** [comment]
Hi
Thank you for your reply
I have successfully run your program, and it give a better result. But i got a problem, if there are some similar scenes(in different position), it will get a error loop closure. In addition to the reduction threshold(actually it will result in getting less closed loop), do you have any ideas to improve the algorithm ? Thank you

**Comment by kissb2** [comment]
Reading the below papers would help you.
- 12 IROS Switchable Constraints for Robust Pose Graph SLAM
- 13 ICRA Robust Map Optimization using Dynamic Covariance Scaling

This research topic is called "robust back-end"

This kind of robust optimizer makes a complete map while false loop factors exist. 
Therefore a loop detector (i.e., front-end) could increase its threshold and takes more true loop factors so that multiple loops are well closed.  

This is our SLAM example integrated Scan Context with robust back-end
- https://github.com/irapkaist/SC-LeGO-LOAM

The specific code line the robust backend used is:
- https://github.com/irapkaist/SC-LeGO-LOAM/blob/18c681df79b6d46f153aac4b7b5362cd5353c22c/SC-LeGO-LOAM/LeGO-LOAM/src/mapOptmization.cpp#L994

**Comment by monage2018** [comment]
Hi,
I try the algorithm of the papers you mentioned above, it's amazing!!! The wrong loop closure are completely eliminated!
So wonderful the switchable loop closure costfunction is !!!!
Thank you, It's like pouring water into the roof.

**Comment by kissb2** [comment]
I am happy to hear that :)
