### ISSUE TITLE
The algorithm is different from the original paper

### ISSUE THREAD

**Issue by monage2018** [irapkaist/scancontext#9]
In the original paper IROS18(Section III, A. Scan Context), it says"For robust recognition over translation, we leverage scan context augmentation through root shifting", and set Ntrans=8, but the code doesn't reflect this point.

**Comment by monage2018** [comment]
And the ring key function is also a little different, in the paper, it using L0 norm, in the code, using L1 norm.

**Comment by kissb2** [comment]
First of all, I am very grateful that you have a kind and detailed look at our paper.
You mentioned are all right, and not implemented in this version of the code, and the reasons:

1. root shifting 
- The root shifting requires multiple point cloud transformation and making descriptors again; (so requires x8 times and memories) so we omitted this process in this version of the repository. 
- For the real-world SLAM application (e.g., https://github.com/irapkaist/SC-LeGO-LOAM), root-shifting is a redundant process in my personal opinion; because if a robot revisits enough places such as a (partial) same route (e.g., https://youtu.be/p-NsVs8GATA), the robot would have enough loop candidates as it is, so global map correction could be easily completed without time-consuming root-shiftings. 

2. ring key function 
- We note that the only requirement for the ring key function is a rotation-invariant and both L0 and L1 meet the condition. And also, we found (after the IROS18 paper) that the L1 (mean) is more generally and empirically efficient for the other modality (e.g., radar, see our ICRA20 paper https://sites.google.com/view/mulran-pr/radar-place-recognition), whose zero measurements are rare. 

I hope this would help you.
